// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact           = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined          = require("bs-platform/lib/js/js_undefined.js");
var ReactNativeMaterialUi = require("react-native-material-ui");

function make(uiTheme, children) {
  return ReasonReact.wrapJsForReason(ReactNativeMaterialUi.ThemeProvider, {
              uiTheme: {
                palette: {
                  primaryColor: uiTheme[/* palette */0][/* primaryColor */0]
                }
              }
            }, children);
}

var ThemeProvider = /* module */[/* make */make];

function make$1(actions, onPress, onLongPress, hidden, icon, transition, style, children) {
  return ReasonReact.wrapJsForReason(ReactNativeMaterialUi.ActionButton, {
              actions: Js_undefined.from_opt(actions),
              onPress: Js_undefined.from_opt(onPress),
              onLongPress: Js_undefined.from_opt(onLongPress),
              hidden: hidden && hidden[0] !== 0 ? true : false,
              icon: Js_undefined.from_opt(icon),
              transition: Js_undefined.from_opt(transition ? (
                      transition[0] !== 0 ? /* Some */["speedDial"] : /* Some */["toolbar"]
                    ) : /* None */0),
              style: Js_undefined.from_opt(style)
            }, children);
}

var ActionButton = /* module */[/* make */make$1];

function make$2(divider, onPress, centerElement, leftElement, rightElement, children) {
  var tmp;
  if (centerElement) {
    var centerElement$1 = centerElement[0];
    var dict = { };
    dict["primaryText"] = centerElement$1[/* primaryText */0];
    var match = centerElement$1[/* secondaryText */1];
    if (match) {
      dict["secondaryText"] = match[0];
    }
    tmp = /* Some */[dict];
  } else {
    tmp = /* None */0;
  }
  return ReasonReact.wrapJsForReason(ReactNativeMaterialUi.ListItem, {
              divider: divider && divider[0] !== 0 ? true : false,
              onPress: Js_undefined.from_opt(onPress),
              centerElement: Js_undefined.from_opt(tmp),
              leftElement: Js_undefined.from_opt(leftElement),
              rightElement: Js_undefined.from_opt(rightElement)
            }, children);
}

var ListItem = /* module */[/* make */make$2];

function make$3(text, inset, lines, children) {
  return ReasonReact.wrapJsForReason(ReactNativeMaterialUi.Subheader, {
              text: text,
              inset: inset && inset[0] !== 0 ? true : false,
              lines: Js_undefined.from_opt(lines)
            }, children);
}

var Subheader = /* module */[/* make */make$3];

function make$4(color, underlayColor, maxOpacity, percent, disabled, size, name, onPress, children) {
  return ReasonReact.wrapJsForReason(ReactNativeMaterialUi.IconToggle, {
              color: Js_undefined.from_opt(color),
              maxOpacity: Js_undefined.from_opt(maxOpacity),
              percent: Js_undefined.from_opt(percent),
              underlayColor: Js_undefined.from_opt(underlayColor),
              disabled: disabled && disabled[0] !== 0 ? true : false,
              size: Js_undefined.from_opt(size),
              name: name,
              onPress: Js_undefined.from_opt(onPress)
            }, children);
}

var IconToggle = /* module */[/* make */make$4];

function optionBoolToJsBool(option) {
  if (option && option[0] !== 0) {
    return true;
  } else {
    return false;
  }
}

function make$5(disabled, raised, primary, accent, onPress, onLongPress, text, upperCase, icon, style, children) {
  return ReasonReact.wrapJsForReason(ReactNativeMaterialUi.Button, {
              disabled: optionBoolToJsBool(disabled),
              raised: optionBoolToJsBool(raised),
              primary: optionBoolToJsBool(primary),
              accent: optionBoolToJsBool(accent),
              onPress: Js_undefined.from_opt(onPress),
              onLongPress: Js_undefined.from_opt(onLongPress),
              text: text,
              upperCase: Js_undefined.from_opt(upperCase),
              icon: Js_undefined.from_opt(icon),
              style: Js_undefined.from_opt(style)
            }, children);
}

var Button = /* module */[/* make */make$5];

exports.ThemeProvider      = ThemeProvider;
exports.ActionButton       = ActionButton;
exports.ListItem           = ListItem;
exports.Subheader          = Subheader;
exports.IconToggle         = IconToggle;
exports.optionBoolToJsBool = optionBoolToJsBool;
exports.Button             = Button;
/* ReasonReact Not a pure module */
